---
###
### Proxy Injector
###
---
{{ $_ := set .Values.global.proxy "workloadKind" "deployment" -}}
{{ $_ := set .Values.global.proxy "component" "linkerd-proxy-injector" -}}
{{ include "linkerd.proxy.validation" .Values.global.proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
  labels:
    app.kubernetes.io/name: proxy-injector
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: {{default .Values.global.linkerdVersion .Values.global.controllerImageVersion}}
    {{.Values.global.controllerComponentLabel}}: proxy-injector
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  name: linkerd-proxy-injector
  namespace: {{.Values.global.namespace}}
spec:
  replicas: {{.Values.controllerReplicas}}
  selector:
    matchLabels:
      {{.Values.global.controllerComponentLabel}}: proxy-injector
  {{- if .Values.enablePodAntiAffinity }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if empty .Values.global.cliVersion }}
        checksum/config: {{ include (print $.Template.BasePath "/proxy-injector-rbac.yaml") . | sha256sum }}
        {{- end }}
        {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
        {{- include "partials.proxy.annotations" .Values.global.proxy| nindent 8}}
      labels:
        {{.Values.global.controllerComponentLabel}}: proxy-injector
        {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
        {{.Values.global.workloadNamespaceLabel}}: {{.Values.global.namespace}}
        {{- include "partials.proxy.labels" .Values.global.proxy | nindent 8}}
    spec:
      {{- if .Values.tolerations -}}
      {{- include "linkerd.tolerations" . | nindent 6 }}
      {{- end -}}
      {{- include "linkerd.node-selector" . | nindent 6 }}
      {{- if .Values.enablePodAntiAffinity -}}
      {{- $local := dict "component" "proxy-injector" "label" .Values.global.controllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - proxy-injector
        - -log-level={{.Values.global.controllerLogLevel}}
        - -controller-namespace={{.Values.global.namespace}}
        - -cni-enabled={{.Values.global.cniEnabled}}
        - -identity-trust-domain={{.Values.global.identityTrustDomain}}
        - -identity-issuance-lifetime={{.Values.identity.issuer.issuanceLifetime}}
        - -identity-clock-skew-allowance={{.Values.identity.issuer.clockSkewAllowance}}
        - -identity-trust-anchors-pem={{b64enc .Values.global.identityTrustAnchorsPEM}}
        - -identity-scheme={{.Values.identity.issuer.scheme}}
        - -omit-webhook-side-effects={{.Values.omitWebhookSideEffects}}
        - -cluster-domain={{.Values.global.clusterDomain}}
        - -proxy-image={{.Values.global.proxy.image.name}}
        - -proxy-image-pull-policy={{.Values.global.proxy.image.pullPolicy}}
        - -proxy-init-image={{.Values.global.proxyInit.image.name}}
        - -proxy-init-image-pull-policy={{.Values.global.proxyInit.image.pullPolicy}}
        - -control-port={{.Values.global.proxy.ports.control}}
        - -ignore-inbound-ports={{.Values.global.proxyInit.ignoreInboundPorts}}
        - -ignore-outbound-ports={{.Values.global.proxyInit.ignoreOutboundPorts}}
        - -inbound-port={{.Values.global.proxy.ports.inbound}}
        - -admin-port={{.Values.global.proxy.ports.admin}}
        - -outbound-port={{.Values.global.proxy.ports.outbound}}
        - -proxy-cpu-request={{.Values.global.proxy.resources.cpu.request}}
        - -proxy-cpu-limit={{.Values.global.proxy.resources.cpu.limit}}
        - -proxy-memory-request={{.Values.global.proxy.resources.memory.request}}
        - -proxy-memory-limit={{.Values.global.proxy.resources.memory.limit}}
        - -proxy-uid={{.Values.global.proxy.uid}}
        - -proxy-log-level={{.Values.global.proxy.logLevel}}
        - -proxy-log-format={{.Values.global.proxy.logFormat}}
        - -enable-external-profiles={{.Values.global.proxy.enableExternalProfiles}}
        - -proxy-version={{.Values.global.proxy.image.version}}
        - -proxy-init-image-version={{.Values.global.proxyInit.image.version}}
        - -debug-image={{.Values.debugContainer.image.name}}
        - -debug-image-pull-policy={{.Values.debugContainer.image.pullPolicy}}
        - -debug-image-version={{.Values.debugContainer.image.version}}
        - -destination-get-networks={{.Values.global.proxy.destinationGetNetworks}}
        - -outbound-connect-timeout={{.Values.global.proxy.outboundConnectTimeout}}
        - -inbound-connect-timeout={{.Values.global.proxy.inboundConnectTimeout}}
        image: {{.Values.controllerImage}}:{{default .Values.global.linkerdVersion .Values.global.controllerImageVersion}}
        imagePullPolicy: {{.Values.global.imagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9995
          initialDelaySeconds: 10
        name: proxy-injector
        ports:
        - containerPort: 8443
          name: proxy-injector
        - containerPort: 9995
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9995
        {{- if .Values.proxyInjectorResources -}}
        {{- include "partials.resources" .Values.proxyInjectorResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.controllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/tls
          name: tls
          readOnly: true
      {{- $tree := deepCopy . }}      
      {{- if not (empty .Values.proxyInjectorProxyResources) }}
      {{- $r := merge .Values.proxyInjectorProxyResources .Values.global.proxy.resources }}
      {{- $_ := set $tree.Values.global.proxy "resources" $r }}
      {{- end }}
      - {{- include "partials.proxy" $tree | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .Values.global.cniEnabled -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-proxy-injector
      volumes:
      - name: tls
        secret:
          secretName: linkerd-proxy-injector-tls
      {{ if .Values.global.controlPlaneTracing -}}
      - {{- include "partials.proxy.volumes.labels" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      {{ if not .Values.global.cniEnabled -}}
      - {{- include "partials.proxyInit.volumes.xtables" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-proxy-injector
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: proxy-injector
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.global.controllerComponentLabel}}: proxy-injector
  ports:
  - name: proxy-injector
    port: 443
    targetPort: proxy-injector
